[2025-08-08T17:10:24.987-0300] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: avisos_coordenador.buscar_variaveis_avisos manual__2025-08-08T20:09:26.243666+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
