[2025-07-31T17:05:39.230-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-31T17:05:39.238-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.baixar_csv_gcs manual__2025-07-31T20:04:57.619785+00:00 [queued]>
[2025-07-31T17:05:39.242-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.baixar_csv_gcs manual__2025-07-31T20:04:57.619785+00:00 [queued]>
[2025-07-31T17:05:39.242-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-31T17:05:39.249-0300] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): baixar_csv_gcs> on 2025-07-31 20:04:57.619785+00:00
[2025-07-31T17:05:39.255-0300] {standard_task_runner.py:63} INFO - Started process 469 to run task
[2025-07-31T17:05:39.257-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exportar_bq_para_gcs_csv', 'baixar_csv_gcs', 'manual__2025-07-31T20:04:57.619785+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/notas_ordem.py', '--cfg-path', '/tmp/tmpwv_jn8k2']
[2025-07-31T17:05:39.258-0300] {standard_task_runner.py:91} INFO - Job 8: Subtask baixar_csv_gcs
[2025-07-31T17:05:39.282-0300] {task_command.py:426} INFO - Running <TaskInstance: exportar_bq_para_gcs_csv.baixar_csv_gcs manual__2025-07-31T20:04:57.619785+00:00 [running]> on host 2778f3f60c85
[2025-07-31T17:05:39.326-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exportar_bq_para_gcs_csv' AIRFLOW_CTX_TASK_ID='baixar_csv_gcs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T20:04:57.619785+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T20:04:57.619785+00:00'
[2025-07-31T17:05:39.327-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-31T17:05:39.335-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-31T17:05:39.336-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        gsutil cp gs://***_vps/nota_ordem.csv.gz /opt/***/csv/nota_ordem.csv.gz\n    ']
[2025-07-31T17:05:39.348-0300] {subprocess.py:86} INFO - Output:
[2025-07-31T17:05:39.349-0300] {subprocess.py:93} INFO - /usr/bin/bash: line 2: gsutil: command not found
[2025-07-31T17:05:39.350-0300] {subprocess.py:97} INFO - Command exited with return code 127
[2025-07-31T17:05:39.350-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-31T17:05:39.356-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-07-31T17:05:39.359-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=exportar_bq_para_gcs_csv, task_id=baixar_csv_gcs, run_id=manual__2025-07-31T20:04:57.619785+00:00, execution_date=20250731T200457, start_date=20250731T200539, end_date=20250731T200539
[2025-07-31T17:05:39.365-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task baixar_csv_gcs (Bash command failed. The command returned a non-zero exit code 127.; 469)
[2025-07-31T17:05:39.389-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-31T17:05:39.405-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-31T17:05:39.406-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
