[2025-07-31T15:37:58.725-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-31T15:37:58.884-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.exportar_tabela_bq_gcs manual__2025-07-31T18:37:54.531815+00:00 [queued]>
[2025-07-31T15:37:58.897-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.exportar_tabela_bq_gcs manual__2025-07-31T18:37:54.531815+00:00 [queued]>
[2025-07-31T15:37:58.898-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-31T15:37:58.923-0300] {taskinstance.py:2330} INFO - Executing <Task(BigQueryToGCSOperator): exportar_tabela_bq_gcs> on 2025-07-31 18:37:54.531815+00:00
[2025-07-31T15:37:58.933-0300] {standard_task_runner.py:63} INFO - Started process 186 to run task
[2025-07-31T15:37:58.937-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exportar_bq_para_gcs_csv', 'exportar_tabela_bq_gcs', 'manual__2025-07-31T18:37:54.531815+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/notas_ordem.py', '--cfg-path', '/tmp/tmpwqx7zo_p']
[2025-07-31T15:37:58.940-0300] {standard_task_runner.py:91} INFO - Job 7: Subtask exportar_tabela_bq_gcs
[2025-07-31T15:37:59.005-0300] {task_command.py:426} INFO - Running <TaskInstance: exportar_bq_para_gcs_csv.exportar_tabela_bq_gcs manual__2025-07-31T18:37:54.531815+00:00 [running]> on host e3648b0a9fa2
[2025-07-31T15:37:59.133-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exportar_bq_para_gcs_csv' AIRFLOW_CTX_TASK_ID='exportar_tabela_bq_gcs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T18:37:54.531815+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T18:37:54.531815+00:00'
[2025-07-31T15:37:59.135-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-31T15:37:59.200-0300] {bigquery_to_gcs.py:201} INFO - Executing extract of sz-00022-ws.PLAMI.NOTAS_ORDENS into: ['gs://***_vps/nota_ordem.csv']
[2025-07-31T15:37:59.211-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-31T15:37:59.227-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/transfers/bigquery_to_gcs.py", line 206, in execute
    hook = BigQueryHook(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 159, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/common/hooks/base_google.py", line 252, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2025-07-31T15:37:59.235-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=exportar_bq_para_gcs_csv, task_id=exportar_tabela_bq_gcs, run_id=manual__2025-07-31T18:37:54.531815+00:00, execution_date=20250731T183754, start_date=20250731T183758, end_date=20250731T183759
[2025-07-31T15:37:59.253-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task exportar_tabela_bq_gcs (The conn_id `google_cloud_default` isn't defined; 186)
[2025-07-31T15:37:59.269-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-31T15:37:59.292-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-31T15:37:59.294-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
