[2025-07-31T17:23:28.069-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-31T17:23:28.077-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.baixar_csv_gcs manual__2025-07-31T20:23:02.073198+00:00 [queued]>
[2025-07-31T17:23:28.082-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.baixar_csv_gcs manual__2025-07-31T20:23:02.073198+00:00 [queued]>
[2025-07-31T17:23:28.082-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-31T17:23:28.088-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): baixar_csv_gcs> on 2025-07-31 20:23:02.073198+00:00
[2025-07-31T17:23:28.094-0300] {standard_task_runner.py:63} INFO - Started process 689 to run task
[2025-07-31T17:23:28.096-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exportar_bq_para_gcs_csv', 'baixar_csv_gcs', 'manual__2025-07-31T20:23:02.073198+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/notas_ordem.py', '--cfg-path', '/tmp/tmpj9hl0z6e']
[2025-07-31T17:23:28.097-0300] {standard_task_runner.py:91} INFO - Job 14: Subtask baixar_csv_gcs
[2025-07-31T17:23:28.121-0300] {task_command.py:426} INFO - Running <TaskInstance: exportar_bq_para_gcs_csv.baixar_csv_gcs manual__2025-07-31T20:23:02.073198+00:00 [running]> on host 2778f3f60c85
[2025-07-31T17:23:28.166-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exportar_bq_para_gcs_csv' AIRFLOW_CTX_TASK_ID='baixar_csv_gcs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T20:23:02.073198+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T20:23:02.073198+00:00'
[2025-07-31T17:23:28.168-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-31T17:23:28.604-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-31T17:23:28.605-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/notas_ordem.py", line 12, in baixar_csv_para_csv_dir
    blob.download_to_filename('./csv/nota_ordem.csv.gz')
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 1312, in download_to_filename
    self._handle_filename_and_download(
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/storage/blob.py", line 1187, in _handle_filename_and_download
    with open(filename, "wb") as file_obj:
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: './csv/nota_ordem.csv.gz'
[2025-07-31T17:23:28.621-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=exportar_bq_para_gcs_csv, task_id=baixar_csv_gcs, run_id=manual__2025-07-31T20:23:02.073198+00:00, execution_date=20250731T202302, start_date=20250731T202328, end_date=20250731T202328
[2025-07-31T17:23:28.635-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task baixar_csv_gcs ([Errno 13] Permission denied: './csv/nota_ordem.csv.gz'; 689)
[2025-07-31T17:23:28.669-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-31T17:23:28.684-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-31T17:23:28.686-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
