[2025-07-31T17:56:06.123-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-31T17:56:06.133-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.carregar_csv_postgres manual__2025-07-31T20:55:45.860029+00:00 [queued]>
[2025-07-31T17:56:06.138-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exportar_bq_para_gcs_csv.carregar_csv_postgres manual__2025-07-31T20:55:45.860029+00:00 [queued]>
[2025-07-31T17:56:06.138-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-31T17:56:06.145-0300] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): carregar_csv_postgres> on 2025-07-31 20:55:45.860029+00:00
[2025-07-31T17:56:06.152-0300] {standard_task_runner.py:63} INFO - Started process 265 to run task
[2025-07-31T17:56:06.154-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exportar_bq_para_gcs_csv', 'carregar_csv_postgres', 'manual__2025-07-31T20:55:45.860029+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/notas_ordem.py', '--cfg-path', '/tmp/tmpbbgu1o7h']
[2025-07-31T17:56:06.155-0300] {standard_task_runner.py:91} INFO - Job 31: Subtask carregar_csv_postgres
[2025-07-31T17:56:06.178-0300] {task_command.py:426} INFO - Running <TaskInstance: exportar_bq_para_gcs_csv.carregar_csv_postgres manual__2025-07-31T20:55:45.860029+00:00 [running]> on host 9a057a876820
[2025-07-31T17:56:06.223-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='exportar_bq_para_gcs_csv' AIRFLOW_CTX_TASK_ID='carregar_csv_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T20:55:45.860029+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T20:55:45.860029+00:00'
[2025-07-31T17:56:06.224-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-31T17:56:06.230-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-31T17:56:06.230-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        gunzip -c /opt/***/csv/nota_ordem.csv.gz |         psql "$PG_CONN" -c         "COPY notas_ordem FROM STDIN DELIMITER E\'\\x1f\' CSV HEADER;"\n    ']
[2025-07-31T17:56:06.242-0300] {subprocess.py:86} INFO - Output:
[2025-07-31T17:56:06.272-0300] {subprocess.py:93} INFO - psql: error: could not translate host name "host" to address: Temporary failure in name resolution
[2025-07-31T17:56:06.273-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2025-07-31T17:56:06.273-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-31T17:56:06.278-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-07-31T17:56:06.280-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=exportar_bq_para_gcs_csv, task_id=carregar_csv_postgres, run_id=manual__2025-07-31T20:55:45.860029+00:00, execution_date=20250731T205545, start_date=20250731T205606, end_date=20250731T205606
[2025-07-31T17:56:06.288-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task carregar_csv_postgres (Bash command failed. The command returned a non-zero exit code 2.; 265)
[2025-07-31T17:56:06.326-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-31T17:56:06.348-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-31T17:56:06.350-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
